events {}

http {
  include mime.types;

  server {
    listen 80;
    listen [::]:80;
    server_name job.almari;

    location / {
      proxy_pass http://jobhunt:3001;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 80;
    listen [::]:80;
    server_name saniajamil.com www.saniajamil.com;

    root /usr/share/nginx/html/portfolio;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location ~ /\. {
      deny all;
    }

    location ~* \.(json|yml|yaml|env|config|py|sh|sql)$ {
      deny all;
    }
  }

}
