events {}

http {
  include mime.types;

  server {
    listen 80;
    server_name saniajamill.com www.saniajamill.com;

    root /usr/share/nginx/html/portfolio;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
