events {}

http {
  include mime.types;

  server {
    listen 80;
    listen [::]:80;
    server_name staging.saniajamil.com;

    root /usr/share/nginx/html/staging;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location ~ /\. {
      deny all;
    }

    location ~* \.(json|yml|yaml|env|config|py|sh|sql)$ {
      deny all;
    }
  }
}
