name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: C:\Users\Hello\home_server\playground

    steps:
      - name: Pull latest changes
        run: git pull origin main

      - name: Restart nginx
        run: docker compose restart nginx
